# TODO: 在此补全参数
planner_server:
  ros__parameters:
    costmap_topic: 
    local_costmap_topic:
    path_topic:
    plugin_name:
    plugin_type:

    AStar:
      lethal_cost:
      cost_weight:

esdf_map_publisher:
  ros__parameters:
    map_yaml:
    frame_id: "map"
    publish_rate_hz: 1.0
    unknown_as_obstacle: false
    robot_radius: 
    margin:
    d_safe:
    w:
    unknown_cost:
    visualize_esdf: false

controller_server:
  ros__parameters:
    local_path_topic:
    odom_topic:
    odom_frame_id:
    map_frame_id: "map"
    cmd_vel_topic:
    base_frame_id: "base_link"
    control_frequency: 50.0

    plugin_name:
    plugin_type:

    PidController:
      base_frame_id: "base_link"

sp_decision:
  ros__parameters:
    tick_rate_hz: 10.0
    tree_files:
      - "sp_decision/decision_trees/click_nav.xml"
    bt_plugins:
      - "nav_to_pose_bt_node"
      - "condition_judge_bt_node"
      - "wait_duration_bt_node"
      - "gimbal_control_bt_node"
      - "chassis_mode_bt_node"
      - "set_double_bt_node"

nav_interface_node:
  ros__parameters:
    default_bt_xml: "sp_nav_bt/nav_bt/default_nav_with_fallback.xml"
    enable_bt_cout_logger: false
    bt_plugins:
      - "nav_compute_path_service"
      - "nav_state_track"
      - "nav_rate_control"
      - "nav_repeat_sequence"
      - "nav_get_pose"
      - "nav_set_control_enable"
